import type { Role, Permission, RoleConfig, DemoAccount } from "@/types/auth"

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  super_admin: [
    "manage_users",
    "create_departments",
    "create_organizations",
    "create_vendors",
    "create_auditors",
    "assign_roles",
    "manage_states",
    "manage_districts",
    "manage_projects",
    "monitor_every_project",
    "view_ai_analytics",
    "view_fraud_alerts",
    "system_configuration",
    "api_configuration",
    "audit_logs",
    "activity_logs",
    "database_monitoring",
    "ai_model_monitoring",
    "data_sync_monitoring",
    "gov_datasets",
    "platform_settings",
    // Inherits viewing capability
    "view_dept_projects",
    "view_assigned_projects",
    "review_auditor_findings",
    "search_public_projects",
  ],
  government: [
    "view_dept_projects",
    "upload_dept_documents",
    "review_ai_analysis",
    "approve_reports",
    "monitor_dept_timelines",
    "assign_inspections",
    "generate_dept_reports",
    "view_district_analytics",
    "department_risk_dashboard",
    "view_ai_analytics",
    "search_public_projects",
  ],
  vendor: [
    "view_assigned_projects",
    "upload_progress_reports",
    "upload_invoices",
    "upload_site_images",
    "upload_drone_footage",
    "upload_completion_certs",
    "track_ai_verification",
    "respond_ai_findings",
    "view_vendor_project_status",
    "view_vendor_payments",
    "view_vendor_milestones",
    "search_public_projects",
  ],
  auditor: [
    "review_auditor_findings",
    "compare_documents",
    "verify_fraud_alerts",
    "schedule_inspections",
    "upload_inspection_reports",
    "upload_field_photos",
    "compare_previous_inspections",
    "generate_audit_reports",
    "view_ai_analytics",
    "search_public_projects",
  ],
  citizen: [
    "search_public_projects",
    "view_public_projects",
    "view_project_progress",
    "view_project_location",
    "view_completion_percentage",
    "view_ai_transparency_score",
    "submit_complaints",
    "upload_complaint_photos",
    "track_complaint",
  ],
}

export const ROLE_CONFIGS: Record<Role, RoleConfig> = {
  super_admin: {
    id: "super_admin",
    name: "Super Administrator",
    shortTitle: "Super Admin",
    badgeText: "👑 Super Admin",
    redirectPath: "/admin",
    accentColor: "amber",
    themeClass: "from-amber-500/20 via-primary/10 to-background",
    borderClass: "border-amber-500/40",
    bgGlowClass: "bg-amber-500/10",
    iconName: "ShieldAlert",
    description: "National Platform Administrator with complete system control, user management, & AI oversight.",
    targetAudience: "Cabinet Secretariat & National Oversight Officers",
    permissionsSummary: [
      "Manage platform users & assign roles across all departments",
      "Configure AI models, fraud alert engines & API integrations",
      "Monitor database sync, live India state analytics & server status",
    ],
    dashboardTitle: "National Command & Operations Center",
    dashboardSubtitle: "Real-time surveillance across 1,284 infrastructure projects and ₹48,200 Cr in public funds.",
  },
  government: {
    id: "government",
    name: "Government Officer / Department Admin",
    shortTitle: "Govt Officer",
    badgeText: "🏛 Government Officer",
    redirectPath: "/government",
    accentColor: "blue",
    themeClass: "from-blue-500/20 via-primary/10 to-background",
    borderClass: "border-blue-500/40",
    bgGlowClass: "bg-blue-500/10",
    iconName: "Landmark",
    description: "Departmental oversight, milestone approvals, document reviews & inspector assignments.",
    targetAudience: "PWD, Smart City, Highways, Municipal & Water Boards",
    permissionsSummary: [
      "Monitor department-specific project progress & budgets",
      "Review AI verification findings & approve milestone reports",
      "Dispatch auditors and generate district risk assessments",
    ],
    dashboardTitle: "Departmental Operations Dashboard",
    dashboardSubtitle: "Public Works & Urban Infrastructure Command for Telangana Region",
  },
  vendor: {
    id: "vendor",
    name: "Vendor / Contractor / Builder",
    shortTitle: "Vendor / Builder",
    badgeText: "🏗 Vendor / Contractor",
    redirectPath: "/vendor",
    accentColor: "emerald",
    themeClass: "from-emerald-500/20 via-primary/10 to-background",
    borderClass: "border-emerald-500/40",
    bgGlowClass: "bg-emerald-500/10",
    iconName: "Building2",
    description: "Execution partner hub for site proof uploads, drone footage, invoice tracking & milestone payouts.",
    targetAudience: "Infrastructure Contractors & Engineering Partners",
    permissionsSummary: [
      "Upload geotagged field photos, drone footage & invoices",
      "Track AI document verification & respond to flagged queries",
      "View disbursement timelines, approved payouts & milestones",
    ],
    dashboardTitle: "Infrastructure Partner Portal",
    dashboardSubtitle: "ABC Infrastructure Ltd — Active Contracts Execution Hub",
  },
  auditor: {
    id: "auditor",
    name: "Auditor / Inspection Team",
    shortTitle: "Forensic Auditor",
    badgeText: "🔎 Forensic Auditor",
    redirectPath: "/auditor",
    accentColor: "rose",
    themeClass: "from-rose-500/20 via-primary/10 to-background",
    borderClass: "border-rose-500/40",
    bgGlowClass: "bg-rose-500/10",
    iconName: "ScanSearch",
    description: "Independent audit unit for fraud verification, satellite image comparison & site inspection.",
    targetAudience: "CAG, Technical Auditors & Quality Assurance Inspectors",
    permissionsSummary: [
      "Review AI neural mesh fraud alerts & evidence anomalies",
      "Compare satellite images vs ground contractor photographs",
      "Schedule physical field visits & issue certified audit reports",
    ],
    dashboardTitle: "Forensic Audit & Inspection Suite",
    dashboardSubtitle: "National Infrastructure Integrity & Anti-Fraud Verification Unit",
  },
  citizen: {
    id: "citizen",
    name: "Citizen / Public Transparency Portal",
    shortTitle: "Public Portal",
    badgeText: "👤 Citizen Portal",
    redirectPath: "/citizen",
    accentColor: "cyan",
    themeClass: "from-cyan-500/20 via-primary/10 to-background",
    borderClass: "border-cyan-500/40",
    bgGlowClass: "bg-cyan-500/10",
    iconName: "Users",
    description: "Public transparency portal to search projects, inspect spending, submit complaints & track issues.",
    targetAudience: "Citizens, RTI Activists & Public Policy Researchers",
    permissionsSummary: [
      "Search any public project and view completion & spending %",
      "Check AI Transparency Rating (Verified / Flagged / Pending)",
      "Submit geo-tagged public grievances & track resolution status",
    ],
    dashboardTitle: "Public Infrastructure Transparency Portal",
    dashboardSubtitle: "Empowering 1.4 Billion citizens with open government spending data.",
  },
}

export const DEMO_ACCOUNTS: DemoAccount[] = [
  {
    role: "super_admin",
    email: "admin@sentinel.gov",
    password: "Admin@123",
    name: "Dr. Rajesh Kumar",
    department: "Cabinet Secretariat",
    organization: "Project Sentinel HQ",
    designation: "National Platform Director",
    badgeText: "👑 Super Admin",
  },
  {
    role: "government",
    email: "pwd.hyderabad@gov.in",
    password: "Govt@123",
    name: "Er. Vikram Reddy",
    department: "Public Works Department (PWD)",
    organization: "Telangana Infrastructure Board",
    designation: "Chief Engineer",
    badgeText: "🏛 Government Officer",
  },
  {
    role: "vendor",
    email: "vendor@abcinfra.com",
    password: "Vendor@123",
    name: "Suresh Mehta",
    department: "Contract Execution",
    organization: "ABC Infrastructure Ltd.",
    designation: "Project Director",
    badgeText: "🏗 Vendor / Contractor",
  },
  {
    role: "auditor",
    email: "auditor@sentinel.gov",
    password: "Audit@123",
    name: "Ananya Sharma",
    department: "CAG Audit Division",
    organization: "National Audit Commission",
    designation: "Forensic Inspector",
    badgeText: "🔎 Forensic Auditor",
  },
  {
    role: "citizen",
    email: "citizen@example.com",
    password: "Citizen@123",
    name: "Aarav Patel",
    department: "Public Transparency",
    organization: "Citizen Sentinel Network",
    designation: "Verified Citizen Member",
    badgeText: "👤 Citizen Portal",
  },
]

export function getPermissionsForRole(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.citizen
}

export function getRoleConfig(role: Role): RoleConfig {
  return ROLE_CONFIGS[role] || ROLE_CONFIGS.citizen
}

export function getRedirectPathForRole(role: Role): string {
  return ROLE_CONFIGS[role]?.redirectPath || "/citizen"
}
