export const MOCK_DEMO_PROJECTS = [
  {
    id: "demo-proj-1",
    _id: "demo-proj-1",
    project: "Demo — Coastal Ring Road Widening",
    department: "Public Works Department",
    state: "Maharashtra",
    district: "Raigad",
    latitude: 18.5,
    longitude: 73.18,
    budget: 1840,
    progress: 62,
    contractor: "Demo Contractor Pvt. Ltd.",
    status: "pending",
    riskScore: 25,
    isDemo: true,
    sourceProvider: "demo",
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "demo-proj-2",
    _id: "demo-proj-2",
    project: "Demo — District Water Treatment Network",
    department: "Jal Shakti Department",
    state: "Rajasthan",
    district: "Jodhpur",
    latitude: 26.29,
    longitude: 73.02,
    budget: 640,
    progress: 48,
    contractor: "Demo Water Works Consortium",
    status: "pending",
    riskScore: 45,
    isDemo: true,
    sourceProvider: "demo",
    createdAt: new Date("2026-01-02T00:00:00.000Z"),
    updatedAt: new Date("2026-01-02T00:00:00.000Z"),
  },
  {
    id: "demo-proj-3",
    _id: "demo-proj-3",
    project: "Demo — Rural Health Sub-Centre Upgrade",
    department: "Department of Health & Family Welfare",
    state: "Bihar",
    district: "Gaya",
    latitude: 24.79,
    longitude: 85.0,
    budget: 210,
    progress: 31,
    contractor: "Demo Buildcon",
    status: "flagged",
    riskScore: 78,
    isDemo: true,
    sourceProvider: "demo",
    createdAt: new Date("2026-01-03T00:00:00.000Z"),
    updatedAt: new Date("2026-01-03T00:00:00.000Z"),
  },
  {
    id: "demo-proj-4",
    _id: "demo-proj-4",
    project: "Demo — Solar Micro-Grid Electrification",
    department: "Ministry of New & Renewable Energy",
    state: "Gujarat",
    district: "Kutch",
    latitude: 23.73,
    longitude: 69.86,
    budget: 1120,
    progress: 78,
    contractor: "Demo Power Systems",
    status: "verified",
    riskScore: 12,
    isDemo: true,
    sourceProvider: "demo",
    createdAt: new Date("2026-01-04T00:00:00.000Z"),
    updatedAt: new Date("2026-01-04T00:00:00.000Z"),
  },
];

export const MOCK_DEMO_DOCUMENTS = [
  {
    id: "demo-doc-1",
    documentId: "demo-doc-1",
    fileName: "coastal_ring_road_audit.pdf",
    originalName: "coastal_ring_road_audit.pdf",
    type: "audit_report",
    status: "analyzed",
    sizeBytes: 1048576,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "demo-doc-2",
    documentId: "demo-doc-2",
    fileName: "water_treatment_invoice.pdf",
    originalName: "water_treatment_invoice.pdf",
    type: "invoice",
    status: "analyzed",
    sizeBytes: 524288,
    createdAt: new Date("2026-01-02T00:00:00.000Z"),
    updatedAt: new Date("2026-01-02T00:00:00.000Z"),
  },
];

export const MOCK_DEMO_REPORT = {
  projectName: "Demo — Coastal Ring Road Widening",
  department: "Public Works Department",
  district: "Raigad",
  contractor: "Demo Contractor Pvt. Ltd.",
  allocatedBudget: "₹1,840 Cr",
  spentAmount: "₹1,140 Cr",
  remainingBudget: "₹700 Cr",
  projectTimeline: "2024 - 2026",
  completionPercentage: "62%",
  transparencyScore: 82,
  riskScore: 25,
  budgetHealth: 80,
  timelineHealth: 75,
  documentationHealth: 90,
  executionHealth: 85,
  riskLevel: "Low Risk",
  invoiceMismatch: false,
  duplicateInvoice: false,
  budgetOverrun: false,
  timelineDelay: false,
  missingEvidence: [],
  anomalies: [],
  recommendations: ["Continue routine quarterly milestones audit."],
  paymentRecommendation: "Approved for current tranche release.",
  confidence: 88,
  executiveSummary: "Project progress aligns well with budget allocations and physical timelines.",
  evidence: ["Submitted verified invoice batch #401", "Site inspection geotag verified"],
  location: { lat: 18.5, lng: 73.18, formattedAddress: "Raigad, Maharashtra" },
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-01-01T00:00:00.000Z"),
};

export const MOCK_DEMO_ACTIVITIES = [
  {
    id: "demo-act-1",
    action: "govdata.sync",
    title: "Government data synced — 4 new project(s) from data.gov.in",
    severity: "low",
    timestamp: new Date("2026-08-02T10:00:00.000Z"),
  },
  {
    id: "demo-act-2",
    action: "project.anomaly_detected",
    title: "AI flagged timeline_delay — Demo — Rural Health Sub-Centre Upgrade",
    severity: "high",
    timestamp: new Date("2026-08-02T09:00:00.000Z"),
  },
  {
    id: "demo-act-3",
    action: "document.analyze",
    title: "AI analysis complete — risk score 25",
    severity: "low",
    timestamp: new Date("2026-08-02T08:00:00.000Z"),
  },
];
