/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTimelineRouteImport } from './routes/_app/timeline'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppInsightsIndexRouteImport } from './routes/_app/insights/index'
import { Route as AppInsightsProjectIdRouteImport } from './routes/_app/insights/$projectId'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppReportsIdRouteImport } from './routes/_app/reports/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInsightsIndexRoute = AppInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInsightsProjectIdRoute = AppInsightsProjectIdRouteImport.update({
  id: '/insights/$projectId',
  path: '/insights/$projectId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
  '/upload': typeof AppUploadRoute
  '/insights/$projectId': typeof AppInsightsProjectIdRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/insights/': typeof AppInsightsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
  '/upload': typeof AppUploadRoute
  '/insights/$projectId': typeof AppInsightsProjectIdRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/insights': typeof AppInsightsIndexRoute
  '/reports': typeof AppReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/insights/$projectId': typeof AppInsightsProjectIdRoute
  '/_app/reports/$id': typeof AppReportsIdRoute
  '/_app/insights/': typeof AppInsightsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/timeline'
    | '/upload'
    | '/insights/$projectId'
    | '/reports/$id'
    | '/insights/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/timeline'
    | '/upload'
    | '/insights/$projectId'
    | '/reports/$id'
    | '/insights'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/timeline'
    | '/_app/upload'
    | '/_app/insights/$projectId'
    | '/_app/reports/$id'
    | '/_app/insights/'
    | '/_app/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/insights/': {
      id: '/_app/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof AppInsightsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/insights/$projectId': {
      id: '/_app/insights/$projectId'
      path: '/insights/$projectId'
      fullPath: '/insights/$projectId'
      preLoaderRoute: typeof AppInsightsProjectIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/$id': {
      id: '/_app/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppUploadRoute: typeof AppUploadRoute
  AppInsightsProjectIdRoute: typeof AppInsightsProjectIdRoute
  AppReportsIdRoute: typeof AppReportsIdRoute
  AppInsightsIndexRoute: typeof AppInsightsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppUploadRoute: AppUploadRoute,
  AppInsightsProjectIdRoute: AppInsightsProjectIdRoute,
  AppReportsIdRoute: AppReportsIdRoute,
  AppInsightsIndexRoute: AppInsightsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
