import type { ProjectMapPoint } from "./api"

/**
 * Shown on the live map only when the backend has no geocoded reports yet
 * (GET /api/projects/map returns an empty list). Replaced automatically the
 * moment real analyzed documents produce location data.
 */
export const DEMO_PROJECT_MAP_POINTS: ProjectMapPoint[] = [
  {
    id: "demo-1",
    lat: 17.6868,
    lng: 83.2185,
    name: "NH-16 Coastal Highway Widening",
    department: "Ministry of Road Transport & Highways",
    district: "Visakhapatnam",
    budget: "₹142 Cr",
    progress: "52%",
    confidence: 94,
    riskScore: 78,
    risk: "high",
    health: 22,
    formattedAddress: "Visakhapatnam, Andhra Pradesh, India",
  },
  {
    id: "demo-2",
    lat: 16.506,
    lng: 80.648,
    name: "Krishna River Barrage Rehabilitation",
    department: "State Irrigation Department",
    district: "Vijayawada",
    budget: "₹86 Cr",
    progress: "64%",
    confidence: 88,
    riskScore: 52,
    risk: "medium",
    health: 48,
    formattedAddress: "Vijayawada, Andhra Pradesh, India",
  },
  {
    id: "demo-3",
    lat: 17.385,
    lng: 78.4867,
    name: "Hyderabad Metro Rail — Phase III",
    department: "Metropolitan Development Authority",
    district: "Hyderabad",
    budget: "₹1,920 Cr",
    progress: "71%",
    confidence: 91,
    riskScore: 31,
    risk: "low",
    health: 69,
    formattedAddress: "Hyderabad, Telangana, India",
  },
  {
    id: "demo-4",
    lat: 12.9716,
    lng: 77.5946,
    name: "Outer Ring Road Flyover Corridor",
    department: "Bengaluru Development Authority",
    district: "Bengaluru Urban",
    budget: "₹410 Cr",
    progress: "83%",
    confidence: 95,
    riskScore: 18,
    risk: "low",
    health: 82,
    formattedAddress: "Bengaluru, Karnataka, India",
  },
  {
    id: "demo-5",
    lat: 13.0827,
    lng: 80.2707,
    name: "Chennai Coastal Desalination Plant",
    department: "Tamil Nadu Water Board",
    district: "Chennai",
    budget: "₹623 Cr",
    progress: "45%",
    confidence: 80,
    riskScore: 58,
    risk: "medium",
    health: 42,
    formattedAddress: "Chennai, Tamil Nadu, India",
  },
  {
    id: "demo-6",
    lat: 19.076,
    lng: 72.8777,
    name: "Mumbai Coastal Road Project",
    department: "Municipal Corporation of Greater Mumbai",
    district: "Mumbai",
    budget: "₹3,200 Cr",
    progress: "38%",
    confidence: 86,
    riskScore: 74,
    risk: "high",
    health: 26,
    formattedAddress: "Mumbai, Maharashtra, India",
  },
  {
    id: "demo-7",
    lat: 28.7041,
    lng: 77.1025,
    name: "Yamuna Riverfront Redevelopment",
    department: "Delhi Development Authority",
    district: "New Delhi",
    budget: "₹210 Cr",
    progress: "57%",
    confidence: 83,
    riskScore: 49,
    risk: "medium",
    health: 51,
    formattedAddress: "New Delhi, Delhi, India",
  },
  {
    id: "demo-8",
    lat: 22.5726,
    lng: 88.3639,
    name: "East-West Metro Corridor Extension",
    department: "Kolkata Metro Rail Corporation",
    district: "Kolkata",
    budget: "₹960 Cr",
    progress: "66%",
    confidence: 90,
    riskScore: 27,
    risk: "low",
    health: 73,
    formattedAddress: "Kolkata, West Bengal, India",
  },
  {
    id: "demo-9",
    lat: 18.5204,
    lng: 73.8567,
    name: "Pune Ring Road Development",
    department: "Public Works Department",
    district: "Pune",
    budget: "₹315 Cr",
    progress: "29%",
    confidence: 76,
    riskScore: 63,
    risk: "medium",
    health: 37,
    formattedAddress: "Pune, Maharashtra, India",
  },
  {
    id: "demo-10",
    lat: 23.0225,
    lng: 72.5714,
    name: "Sabarmati Riverfront — Phase II",
    department: "Ahmedabad Municipal Corporation",
    district: "Ahmedabad",
    budget: "₹178 Cr",
    progress: "88%",
    confidence: 97,
    riskScore: 9,
    risk: "low",
    health: 91,
    formattedAddress: "Ahmedabad, Gujarat, India",
  },
  {
    id: "demo-11",
    lat: 26.9124,
    lng: 75.7873,
    name: "Jaipur Smart City Water Grid",
    department: "Jal Shakti Board",
    district: "Jaipur",
    budget: "₹94 Cr",
    progress: "22%",
    confidence: 68,
    riskScore: 81,
    risk: "high",
    health: 19,
    formattedAddress: "Jaipur, Rajasthan, India",
  },
  {
    id: "demo-12",
    lat: 26.8467,
    lng: 80.9462,
    name: "Rural Health Sub-Centre Upgrade",
    department: "Department of Health & Family Welfare",
    district: "Lucknow",
    budget: "₹41 Cr",
    progress: "34%",
    confidence: 72,
    riskScore: 56,
    risk: "medium",
    health: 44,
    formattedAddress: "Lucknow, Uttar Pradesh, India",
  },
]
